### ISSUE TITLE
Docker Latest Tag

### ISSUE THREAD

**Issue by madhavajay** [apereo/cas-webapp-docker#10]
Hi,
The instructions here on docker hub don't work because there is no "latest" tag:
https://hub.docker.com/r/apereo/cas/

docker pull apereo/cas
Please push the latest version tagged as "latest" and make it part of the docker build and push process.

**Comment by mmoayyed** [comment]
Note that today, Docker Hub is unable to convert an existing repository to use Automated Builds:
https://github.com/docker/hub-feedback/issues/794

Seems like we'd have to delete the existing repo or start a brand new one for the automated build, neither of which is going to happen. We can proceed to do this manually for now until that ability becomes available.

**Comment by mmoayyed** [comment]
This is now done.
