### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by alatriste-lee** [apereo/cas-webapp-docker#11]
:~ xx$ docker start cas

Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"cas-overlay/bin/run-cas.sh\": stat cas-overlay/bin/run-cas.sh: no such file or directory"
Error: failed to start containers: cas

env is mac docker.

**Comment by mmoayyed** [comment]
Make sure the bin directory is copied and has the right permissions.

**Comment by ycrxun** [comment]
env is win10 docker.

```sh
$ docker run -d --name=cas -p 8180:8080 -p 8443:8443 apereo/cas sh /cas-overlay/bin/run-cas.sh
```
