### ISSUE TITLE
Issue on build cas

### ISSUE THREAD

**Issue by sabloger** [apereo/cas-webapp-docker#13]
Hi,
When i run:
`sudo docker exec cas ./build.sh v4.2.1`
See this output:
`rpc error: code = 2 desc = containerd: container not started`

What's wrong??
----
`sudo docker ps` :
`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
f599d89b002c        apereo/cas:v4.2.1   "/cas-overlay/bin/run"   49 minutes ago      Up 49 minutes       8080/tcp, 8443/tcp   cas`

and `sudo docker info` :
`Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.664 GiB
Name: falsafin
ID: P4L2:UI4Y:XDNG:XFZ5:FKHU:2ZLJ:XGJV:GO7D:WA5U:KIFW:K227:5LZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8`

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/developer/Maintenance-Policy.html
