### ISSUE TITLE
Docker build fails because ZuluJCEPolicies.zip Not Found...

### ISSUE THREAD

**Issue by dannymk** [apereo/cas-webapp-docker#15]
Docker version: 17.06.0-ce, build 02c1d87
...
Step 6/16 : RUN cd / 	&& wget http://www.azulsystems.com/sites/default/files/images/ZuluJCEPolicies.zip     && unzip ZuluJCEPolicies.zip     && mv -f ZuluJCEPolicies/*.jar /opt/jre-home/lib/security     && rm ZuluJCEPolicies.zip;
 ---> Running in 925e9df6ae41
--2017-07-21 15:21:10--  http://www.azulsystems.com/sites/default/files/images/ZuluJCEPolicies.zip
Resolving www.azulsystems.com (www.azulsystems.com)... 67.225.185.52
Connecting to www.azulsystems.com (www.azulsystems.com)|67.225.185.52|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.azul.com/sites/default/files/images/ZuluJCEPolicies.zip [following]
--2017-07-21 15:21:11--  https://www.azul.com/sites/default/files/images/ZuluJCEPolicies.zip
Resolving www.azul.com (www.azul.com)... 67.225.185.52
Connecting to www.azul.com (www.azul.com)|67.225.185.52|:443... connected.
**HTTP request sent, awaiting response... 404 Not Found**
2017-07-21 15:21:12 ERROR 404: Not Found.

The command '/bin/sh -c cd / 	&& wget http://www.azulsystems.com/sites/default/files/images/ZuluJCEPolicies.zip     && unzip ZuluJCEPolicies.zip     && mv -f ZuluJCEPolicies/*.jar /opt/jre-home/lib/security     && rm ZuluJCEPolicies.zip;' returned a non-zero code: 8

**Comment by mmoayyed** [comment]
Are you running the most recent version of this repo?

**Comment by mmoayyed** [comment]
Ah, I thought I'd fixed this but perhaps not.  Hang tight for a sec.

**Comment by mmoayyed** [comment]
You can try again now.

**Comment by dannymk** [comment]
Excellent, thank you.  That fixed it!
