### ISSUE TITLE
Cannot build the image because of Oracle JDK dependency

### ISSUE THREAD

**Issue by la-urre** [apereo/cas-webapp-docker#2]
I can't build the image from this Dockerfile. In the command line, I get a "503 Service Unavailable" error. If I visit the corresponding link from my Browser, I get the following error: 

"Thank you for accessing the Oracle Software Delivery Cloud. Due to your country location, we are unable to process your request."

In short I can't build the docker image because I am located in an unauthorized country from Oracle's point of view.

I searched for the JDK in another repository, but with no success.

Do you know another repository to download the JDK ?
Do you think the docker file could be rewritten to use a repository that is more accessible across countries ?

**Comment by mmoayyed** [comment]
You can either try azul or openjdk and change the docker script to pull those in.

**Comment by mmoayyed** [comment]
This is now provided via azul.
