### ISSUE TITLE
New Docker Images?

### ISSUE THREAD

**Issue by jstevensfit** [apereo/cas-webapp-docker#22]
Are you guys planning on publishing the new docker images? The latest docker image I see is 5.2.2, at the time of writing this 5.3.2 is the latest release of cas.

**Comment by mmoayyed** [comment]
Yes. At some point.

**Comment by jstevensfit** [comment]
That was quick, thanks for the info @mmoayyed

**Comment by mmoayyed** [comment]
The image should now be available. There is probably some work that needs to be done to ensure the image size is reduced using multi-stage builds. Feel free to optimize the build: https://github.com/apereo/cas/tree/5.3.x/docker

**Comment by jstevensfit** [comment]
Thanks @mmoayyed I really appreciate it.
