### ISSUE TITLE
README : improve introduction

### ISSUE THREAD

**Issue by la-urre** [apereo/cas-webapp-docker#5]
I would like to have more precisions in the introduction of the README.md file. In particular, I want to know how to use this repo:

* Can I use the image available on dockerhub as is ? If I can, how can I configure it ?
* Do I have to clone this repository to make my own image, in which I will embed my particular config ? And in this case what do I have to do to configure the server web app ? Am I supposed to customize the Dockerfile itself, to add my config files to the overlay project that is cloned from the Dockerfile ?

Maybe a page on the wiki would be the right place to go, but I find the documentation is hard to understand. Maybe the page to improve would be the "Docker Installation" page, more precisely this sentence: "Additional instructions on how to use CAS docker images for deployment and adoption will become available in the future".

**Comment by mmoayyed** [comment]
You are welcome to post a PR and add as much instruction as possible, either here  or the project wiki.
- Depends what you mean by "use". As for how, that's a question for docker if you wish to learn how to use docker images.
- The image on hub is mostly for demo/samples. You are to build your own image based on your own overlay; that is approach implemented here, or you're welcome to choose a different path. 

I can clean up the wiki to explain this a bit more based on the notes here.

**Comment by mmoayyed** [comment]
Updated docs should show up in about 30 mins. Note that [and this is also added to the docs] since the docker image here is based on an existing overlay, your path to victory could be:
1. Prepare an CAS overlay with your customizations
2. Point your docker file to that overlay and build your images.
