### ISSUE TITLE
Can't connect over HTTPS

### ISSUE THREAD

**Issue by kimus** [apereo/cas-webapp-docker#8]
I've started container with:
docker run -p 8080:8080 -p 8443:8443 --name cas apereo/cas:v4.2.1

When trying to go to https://localhost:8443/cas/login it doesn't connect.
http://localhost:8080/cas/login Woks fine.

```bash
$ openssl s_client -connect localhost:8443
CONNECTED(00000003)
16762:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/ssl/s23_lib.c:185
```

**Comment by mmoayyed** [comment]
Please study the readme to generate a keystore

**Comment by llitfkitfk** [comment]
@mmoayyed How to config ssl?

**Comment by raguilera82** [comment]
The easiest way in localhost with sign-self certificate:

`$> cd cas-webapp-docker`
`$> keytool -genkey -keyalg RSA -alias cas -keystore thekeystore -storepass changeit -validity 9999 -keysize 2048`

What is your first and last name?
  [Unknown]: [hostname] //It's important that you put your name machine, in linux/unix you can know with hostname -f command. Note: without brackets
....

**Comment by kimus** [comment]
I was using a pre-build docker image (apereo/cas:v4.2.1 from docker hub), so I was expecting that everything would work out of the box (with a pre-generated key working).

**Comment by jean-io** [comment]
@raguilera82 thank a lot!!!

This is not mentioned anywhere... 

- can you please add it to README in the build section?
- why this is not in `build.sh`?

**Comment by mmoayyed** [comment]
You are expected to generate a keystore yourself.
