### ISSUE TITLE
Accessing the Dashboard

### ISSUE THREAD

**Issue by Xqua** [apereo/cas-webapp-docker#9]
I succesfully created a Docker instance with CAS in it, and I can access it from https://myURL/cas/login 

I can successfully login using casuser/Mellon 

But I cannot access the dashboard https://MyURL/cas/status/dashboard, It says I am not authorized. 

What am I missing here ? 

Thanks

**Comment by mmoayyed** [comment]
You'll need to authorize access to the endpoint. See docs
